### ISSUE TITLE
Angular production build - CSS mixins in component style NOT working properly with Polymer's custom-style

### ISSUE THREAD

**Issue by firstor** [first87/polymer-chat#11]
#### Reproduction
 - Angular 4.2.3
 - Polymer 2
 - Used [origami](https://github.com/hotforfeature/origami/blob/master/docs/custom-style.md) to parse custom CSS variables and mixins in the component style
   ```ts
   /* ========= app.module.ts ========= */
   import {CUSTOM_ELEMENTS_SCHEMA, NgModule} from '@angular/core';
   import {PolymerModule} from '@codebakery/origami';
   ...

   @NgModule({
       ...
       imports: [
           ...
           PolymerModule.forRoot(),
           ...
       ],
       schemas: [CUSTOM_ELEMENTS_SCHEMA],
       ...
   })
   ...
   ```
 - Used CSS-mixins to style `<paper-textarea>` element in an Angular component
   ```html
   <!-- ========= angular.component.html ========= -->
   ...
   <paper-textarea class="form-control message-input-field" ...>
   </paper-textarea>
   ...
   ```
   ```css
   /* ========= angular.component.css ========= */
   .message-input-field {
       --paper-input-container-input-color: var(--app-input-color); /* works fine */
       --paper-input-container-underline: { /* NOT working */
           display: none;
       }
       --paper-input-container-underline-focus: { /* NOT working */
           display: none;
       }
       @apply --app-word-wrapping; /* works fine */
   }
   ```
   ```css
   /* ========= document-level styles ========= */
   --app-word-wrapping: {
     overflow-wrap: break-word;
     word-wrap: break-word;
     -ms-word-wrap: break-word;
     word-break: break-word;
     -ms-word-break: break-word;
   }
   ```

#### Current output (on the browser's inspector)
```css
--paper-input-container-input-color: var(--app-input-color);
--paper-input-container-underline: {display:none}--paper-input-container-underline-focus:{display:none}overflow-wrap: var(--app-word-wrapping_-_overflow-wrap);
word-wrap: var(--app-word-wrapping_-_word-wrap);
-ms-word-wrap: var(--app-word-wrapping_-_-ms-word-wrap);
word-break: var(--app-word-wrapping_-_word-break);
-ms-word-break: var(--app-word-wrapping_-_-ms-word-break);
```

#### Expected output on the inspector
```css
--paper-input-container-input-color: var(--app-input-color);
--paper-input-container-underline_-_display: none;
--paper-input-container-underline-focus_-_display: none;
overflow-wrap: var(--app-word-wrapping_-_overflow-wrap);
word-wrap: var(--app-word-wrapping_-_word-wrap);
-ms-word-wrap: var(--app-word-wrapping_-_-ms-word-wrap);
word-break: var(--app-word-wrapping_-_word-break);
-ms-word-break: var(--app-word-wrapping_-_-ms-word-break);
```

This does happen only in the production build and everything works fine in the development mode. The production build is configured based on [origami's production build guide](https://github.com/hotforfeature/origami/blob/master/docs/production-build.md) and `enableProdMode()` is invoked in the production mode. (See also https://github.com/hotforfeature/origami/tree/master/demo for more detail of my production build configuration)

Not sure if this problem comes from Angular production mode itself or anything else.

**Comment by hotforfeature** [comment]
This is one of those issues developers hate: the dreaded missing semicolon. The "correct" way to write a CSS mixin is with a semicolon at the end:

```css
html {
  --my-mixin: { display: none }; <--
  --might-still-work-but-not-correct: { display: none }
}
```

Angular's production build is minifying the CSS, which ShadyCSS parses at runtime. Unminified with a line break (dev mode), ShadyCSS can parse it. Minified without a line break (prod mode), it needs the semicolon.

The following CSS from your example works for me when I cloned the repo:

app.component.css
```css
html {
  --app-word-wrapping: {
    overflow-wrap: break-word;
    word-wrap: break-word;
    -ms-word-wrap: break-word;
    word-break: break-word;
    -ms-word-break: break-word;
  }; <-- Note this worked without a semicolon because there are no rules following the "improper" mixin
}

.message-input-field {
  --paper-input-container-input-color: var(--app-input-color);
  --paper-input-container-underline: {
    display: none;
  };
  --paper-input-container-underline-focus: {
    display: none;
  };
  @apply --app-word-wrapping;
}
```
